"""背景图处理：转换分辨率/裁剪方式/透明度合成，生成 esp32/background.h。"""
from __future__ import annotations

from pathlib import Path

from PIL import Image

from .app_config import BG_ALPHAS, MENU_BG, SCREEN_H, SCREEN_W


def prepare_image(src: str | Path, mode: str = "cover") -> Image.Image:
    """读取图片并缩放到 240x135。

    mode: stretch=拉伸填满, cover=裁切填满, fit=等比居中留边
    """
    im = Image.open(src).convert("RGB")
    if mode == "stretch":
        return im.resize((SCREEN_W, SCREEN_H), Image.LANCZOS)
    if mode == "fit":
        im.thumbnail((SCREEN_W, SCREEN_H), Image.LANCZOS)
        canvas = Image.new("RGB", (SCREEN_W, SCREEN_H), MENU_BG)
        canvas.paste(
            im,
            ((SCREEN_W - im.width) // 2, (SCREEN_H - im.height) // 2),
        )
        return canvas
    # cover：等比放大后居中裁剪
    scale = max(SCREEN_W / im.width, SCREEN_H / im.height)
    im2 = im.resize(
        (max(1, round(im.width * scale)), max(1, round(im.height * scale))),
        Image.LANCZOS,
    )
    x = (im2.width - SCREEN_W) // 2
    y = (im2.height - SCREEN_H) // 2
    return im2.crop((x, y, x + SCREEN_W, y + SCREEN_H))


def blend_with_bg(im: Image.Image, alpha: float) -> Image.Image:
    """按 alpha 把图片和菜单底色合成（与固件 background_gen.py 一致）。"""
    if alpha >= 1.0:
        return im.copy()
    if alpha <= 0.0:
        return Image.new("RGB", im.size, MENU_BG)
    bg = Image.new("RGB", im.size, MENU_BG)
    return Image.blend(bg, im, alpha)


def preview_image(src: str | Path, mode: str = "cover", alpha: float = 0.55) -> Image.Image:
    """生成用于界面预览的图片（未合成透明度时返回原图缩放结果）。"""
    return blend_with_bg(prepare_image(src, mode), alpha)


def _rgb565(r: int, g: int, b: int) -> int:
    return ((r >> 3) << 11) | ((g >> 2) << 5) | (b >> 3)


def generate_background_header(
    src: str | Path,
    out_path: str | Path,
    mode: str = "cover",
) -> Path:
    """生成与 esp32.ino 期望格式一致的 background.h（5 档透明度）。"""
    im = prepare_image(src, mode)
    pixels = list(im.getdata())
    variants: list[list[int]] = []
    for alpha in BG_ALPHAS:
        blended = blend_with_bg(im, alpha)
        data = [_rgb565(*px) for px in blended.getdata()]
        variants.append(data)

    out = Path(out_path)
    out.parent.mkdir(parents=True, exist_ok=True)
    with out.open("w", encoding="utf-8") as f:
        f.write("#pragma once\n")
        f.write("#include <stdint.h>\n")
        f.write("\n// %dx%d background, generated by GP-Fusion 配置向导\n"
                % (SCREEN_W, SCREEN_H))
        for idx, alpha in enumerate(BG_ALPHAS):
            f.write("// variant %d: image opacity %.2f\n" % (idx, alpha))
            f.write("const uint16_t BACKGROUND_IMG_%d[%d] PROGMEM = {\n"
                    % (idx, SCREEN_W * SCREEN_H))
            data = variants[idx]
            for i in range(0, len(data), 16):
                f.write("  " + ", ".join("0x%04X" % v for v in data[i:i + 16]) + ",\n")
            f.write("};\n\n")
        f.write("#define BACKGROUND_LEVELS %d\n" % len(BG_ALPHAS))
        f.write("const uint16_t *const BACKGROUND_IMG[BACKGROUND_LEVELS] PROGMEM = {\n")
        for idx in range(len(BG_ALPHAS)):
            f.write("  BACKGROUND_IMG_%d,\n" % idx)
        f.write("};\n")
    return out
